# Setup
title:            NuteBurn
tagline:          "A Grow Journal"
description:      "Just some asshole with a blog trying to grow weed. <i>I'm gonna burn the shit out of these plants</i>"
url:              "https://nuteburn.github.io/hyde"
baseurl:          "https://nuteburn.github.io/hyde"
paginate:         5

# About and contact
author:
  name:           "Nute Burn"
  url:            nil

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
