# Setup
title:            NuteBurn
tagline:          'A Grow Journal'
description:      'A brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              'https://nuteburn.github.io/hyde'
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Nute Burn'
  url:            nil

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          1.0.0
