# Setup
title:            NuteBurn
tagline:          "A Grow Journal"
description:      "Just some asshole with a blog trying to grow weed. <br><i>I'm gonna burn the shit out of these plants</i>"
url:              https://nuteburn.com
baseurl:          ""
paginate:         5
github:           https://github.com/NuteBurn/nuteburn.github.io

# About and contact
author:
  name:           "Nute Burn"
  url:            nil

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
