# Setup
title:            NuteBurn
tagline:          "A Grow Journal"
description:      "Just some asshole with a blog trying to grow some dank-ass weed. <br><i>I'm gonna burn the shit out of these plants</i>"
url:              https://nuteburn.com
baseurl:          ""
paginate:         5
shareimage:       https://repository-images.githubusercontent.com/340120407/09e95580-7a93-11eb-965a-337880c1006e

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

Social-Profiles:
  reddit:
    href: https://www.reddit.com/user/Nute-burn
    user: Nute-Burn
    title: Reddit
    fa-icon: fab fa-reddit
  
  github:
    href: https://github.com/NuteBurn/nuteburn.github.io
    user: nuteburn
    title: GitHub
    fa-icon: 'fab fa-github-square'